### PR TITLE
fix: insecure link in readme

### PR DESCRIPTION
**Pull request by OutdatedGuy**
Increases 5 pub points

Screenshot 2023-05-14 at 11 49 07 PM

### CODE REVIEW

**Comment by OutdatedGuy** [comment]
@hnvn, can you review this?

**Comment by freshtechtips** [comment]
> @hnvn, can you review this?

Is the library still maintained?

**Comment by hnvn** [comment]
LGTM

**Comment by freshtechtips** [comment]
> LGTM

Thanks

**Pull request merged**
