### PR TITLE
Updated library

### PR DESCRIPTION
**Pull request by himanshu096**
Added option to change control widget UI color
Changed Android Library

### CODE REVIEW

**Comment by VictorUvarov** [comment]
Does this fix the android crashing issue when cropper is opened? if so please merge this pr.

**Comment by ejprok** [comment]
Also wondering if this fixes the issued on Android as well.

**Comment by himanshu096** [comment]
@VictorUvarov @ejprok You can use the updated library by replacing this code in your pubspec.yaml to test if it's working for you or not.

`  image_cropper:
    git:
      url: git://github.com/devslane/flutter_image_cropper
      ref: master
`

**Comment by himanshu096** [comment]
@VictorUvarov @ejprok You can use the updated library by replacing this code in your pubspec.yaml to test if it's working for you or not.

```
  image_cropper:
    git:
      url: git://github.com/devslane/flutter_image_cropper
      ref: master
```

**Comment by tineo** [comment]
It's working for me :) thanks!

**Comment by hnvn** [comment]
These features are supported now in v1.1.0

**Pull request closed without merging**
