### PR TITLE
add option to enable free range crop

### PR DESCRIPTION
**Pull request by stefanwuest**
This PR adds the option to allow free range cropping. Also see #58

### CODE REVIEW

**Comment by hnvn** [comment]
Cool, but what about iOS?

**Comment by stefanwuest** [comment]
> Cool, but what about iOS?

Good point 😄— I'll have a look at it.

**Comment by stefanwuest** [comment]
@hnvn 
Current behaviour already allows free range cropping on iOS. However, if you add a ratio it will be disabled. We could have `enableFreeRange` override the disabling of the free crop and have the ratio only behave as a default ratio in case both are set. What do you think?

**Comment by Xgamefactory** [comment]
we have tested without adding ratio properties but there is no free crop range in android.

**Comment by stefanwuest** [comment]
> we have tested without adding ratio properties but there is no free crop range in android.

Have you tested this branch and set `enableFreeRange` to `true`?

**Comment by hnvn** [comment]
>Current behaviour already allows free range cropping on iOS. However, if you add a ratio it will be disabled. We could have enableFreeRange override the disabling of the free crop and have the ratio only behave as a default ratio in case both are set. What do you think?

I think we can make the behavior of Android same as the behavior of iOS, enable free-range by default and only disable it if the ratio is set.

**Comment by hnvn** [comment]
This feature is supported now in v1.1.0

**Comment by Xgamefactory** [comment]
there is no enableFreeRange property.
v.1.2.1

> This feature is supported now in v1.1.0

**Comment by SBNTT** [comment]
`lockAspectRatio` attribute of `androidUiSettings` must be set to false :)

**Pull request closed without merging**
