### PR TITLE
fix translation for web ui setting

### PR DESCRIPTION
**Pull request by maah75**
HI this is a fix for Translations in WebUiSettings Please inform me if there is any issue or step need it to be taken before the contribution as this my first ^_^

Thanks

### CODE REVIEW

**Comment by KyoheiNakamura** [comment]
@hnvn 
Hi, this is a very simple change.
Could you please merge this RP?
Thank you very much.🙇‍♂️

**Comment by Taha-WOBY** [comment]
Hello,

Could you please merge this PR ?

Thank you very much.

**Comment by Taha-WOBY** [comment]
Hello @hnvn
Could you please merge this PR 

We need this fix to be added, i have tested locally and it works by exporting the webTranslations so that we can edit the title and the text the of button in the crop pop up

Thank you !

**Comment by Kawan02** [comment]
Hi @hnvn
Could you please merge this PR

We need this fix added, I've tested it locally and it works by exporting the webTranslations so we can edit the title and button text in the crop popup

I looked at pub dev and it doesn't have any updates

Thanks!

**Comment by Kawan02** [comment]
@hnvn  would you please merge this PR

I'm working on a project, where I need you to raise this pr so I can complete the implementation of the image cropping

Thanks!

**Comment by Kawan02** [comment]
> @maah75, parece que este PR ainda não foi concluído ?

Not yet

**Comment by TOUFIK-Taha98** [comment]
@hnvn Could you update this version here please ? 
https://pub.dev/packages/image_cropper

**Comment by Kawan02** [comment]
> @hnvnVocê poderia atualizar esta versão aqui, por favor? https://pub.dev/packages/image_cropper

Up!

Could you update the package over at pub dev please https://pub.dev/packages/image_cropper?

**Pull request merged**
